<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

  <property name="M_PI" value="3.1415926535897931" />

  <property name="caster_wheel_offset_y" value="0.049" /> <!-- from function spreadsheet -->
  <property name="wheel_length" value="0.03" />  <!-- FIXME -->
  <property name="wheel_radius" value="0.074792" />   <!-- This is the 'effective' wheel radius. Wheel radius for uncompressed wheel is 0.079.  mp 20080801 -->

  <!-- based on 090224_link_data from function engineering -->
  <property name="base_cg_x" value="-0.061" />
  <property name="base_cg_y" value="0.0" />
  <property name="base_cg_z" value="0.293" />
  <property name="base_mass" value="116.0" />

  <!-- base appears "raised" from our initial geom def from function -->
  <property name="base_height_offset" value="0.05" />

  <!-- simplified box collision geometry for base -->
  <property name="base_size_x" value="0.65" />
  <property name="base_size_y" value="0.65" />
  <property name="base_size_z" value="0.23" />
  <!-- simplified box collision geometry for hokuyo laser -->
  <property name="base_laser_x" value="0.275" />
  <property name="base_laser_y" value="0.0" />
  <property name="base_laser_z" value="0.252" />
  <property name="base_laser_size_x" value="0.08" />
  <property name="base_laser_size_y" value="0.08" />
  <property name="base_laser_size_z" value="0.03" />
  <property name="base_laser_collision_offset_z" value="0.03" />

  <macro name="pr2_wheel" params="suffix parent reflect">

    <link name="${parent}_${suffix}_wheel_link">
      <joint name="0 0 0" type="0 0 0">
        <axis xyz="0 1 0" />
        <limit effort="100" velocity="100"/>
        <safety_controller k_velocity="10" />
        <joint_properties damping="0.0" friction="0.0" />
        <parent name="${parent}_rotation_link">
          <joint name="${parent}_${suffix}_wheel_joint" type="revolute">
        </parent>
      </joint>
      <origin xyz="0 ${reflect*caster_wheel_offset_y} 0" rpy="0 0 0" />
      <inertial>
        <mass value="0.44036" /> <!-- check jmh 20081205 -->
        <origin xyz=" 0 0 0 " />
        <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                  iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
      </inertial>
      <visual name="${parent}_${suffix}_wheel_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${parent}_${suffix}_wheel_visual_geom">
          <mesh filename="pr2_wheel.stlb" />
        </geometry>

      </visual>
      <collision name="${parent}_${suffix}_wheel_collision">
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry name="${parent}_${suffix}_wheel_collision_geom">
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
      </collision>
    </link>


    <gazebo name="${parent}_${suffix}_wheel_sensor" reference="${parent}_${suffix}_wheel_link">
      <sensor:contact name="${parent}_${suffix}_wheel_contact_sensor">
        <geom>${parent}_${suffix}_wheel_collision</geom>
        <updateRate>100.0</updateRate>
        <controller:ros_bumper name="${parent}_${suffix}_wheel_ros_bumper_controller" plugin="libros_bumper.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>100.0</updateRate>
          <bumperTopicName>${parent}_${suffix}_wheel_bumper</bumperTopicName>
          <interface:bumper name="${parent}_${suffix}_wheel_ros_bumper_iface" />
        </controller:ros_bumper>
      </sensor:contact>
    </gazebo>
    <gazebo name="friction_coefficients" reference="${parent}_${suffix}_wheel_collision">
      <mu1 value="100.0" />
      <mu2 value="100.0" />
      <kp  value="1000000.0" />
      <kd  value="1.0" />
    </gazebo>

    <ogre name="${parent}_${suffix}_wheel_visual_mesh" reference="${parent}_${suffix}_wheel_visual">
      <mesh value="pr2_wheel.mesh" />
    </ogre>
    <ogre name="gazebo_material" reference="${parent}_${suffix}_wheel_visual">
      <!-- TODO should be different for left and right wheel-->
      <material value="PR2/${parent}_${suffix}_wheel_link" />
    </ogre>

    <transmission type="SimpleTransmission" name="${parent}_${suffix}_wheel_trans">
      <actuator name="${parent}_${suffix}_wheel_motor" />
      <joint name="${parent}_${suffix}_wheel_joint" />
      <mechanicalReduction>${reflect*75.05}</mechanicalReduction>
      <calibration values="1.5 -1" />
    </transmission>
  </macro>

  <macro name="pr2_caster" params="suffix parent *origin">


    <link name="${suffix}_caster_rotation_link">
      <joint name="${suffix}_caster_rotation_joint" type="revolute">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="100" velocity="100"/>
        <safety_controller k_velocity="10" />
        <joint_properties damping="0.0" friction="0.0" />
        <parent name="${parent}">
          <insert_block name="origin">
        </parent>
      </joint>

      <inertial>
        <mass value="3.473082" />
        <origin xyz="0 0 0.07" />
        <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                  iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
      </inertial>

      <visual name="${suffix}_caster_rotation_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${suffix}_caster_rotation_visual_geom">
          <mesh filename="caster.stlb" />
        </geometry>
      </visual>

      <collision name="${suffix}_caster_rotation_collision">
        <origin xyz="0 0 0.07" rpy="0.0 0.0 0.0" />
        <geometry name="${suffix}_caster_rotation_collision_geom">
          <box size="0.192 0.164 0.013" />
        </geometry>
      </collision>
    </link>


    <ogre name="${suffix}_caster_rotation_visual_mesh" reference="${suffix}_caster_rotation_visual">
      <elem key="mesh" value="caster.mesh" />
    </ogre>
    <ogre name="gazebo_material" reference="${suffix}_caster_rotation_visual">
      <elem key="material" value="PR2/Green" />
    </ogre>

    <transmission type="SimpleTransmission" name="${suffix}_caster_rotation_trans">
      <actuator name="${suffix}_caster_rotation_motor" />
      <joint name="${suffix}_caster_rotation_joint" />
      <mechanicalReduction>-75.05</mechanicalReduction>
      <calibration reference_position="0.0" values="1.5 -1" />
    </transmission>

    <!-- wheel macros -->
    <pr2_wheel parent="${suffix}_caster" suffix="l" reflect="1" />
    <pr2_wheel parent="${suffix}_caster" suffix="r" reflect="-1" />
  </macro>

  <!--                                                      -->
  <!-- Alpha 2.0 hardware                                   -->
  <!--                                                      -->
  <macro name="pr2_wheel_alpha2" params="suffix parent reflect">

    <link name="${parent}_${suffix}_wheel_link">
      <joint name="${parent}_${suffix}_wheel_joint" type="revolute">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit effort="100" velocity="100"/>
        <safety_controller  k_velocity="10" />
        <joint_properties damping="0.0" friction="0.0" />
        <parent name="${parent}_rotation_link">
          <origin xyz="0 ${reflect*caster_wheel_offset_y} 0" rpy="0 0 0" />
        </parent>
      </joint>
      <inertial>
        <mass value="0.44036" /> <!-- check jmh 20081205 -->
        <origin xyz="0 0 0" />
        <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                  iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
      </inertial>
      <visual name="${parent}_${suffix}_wheel_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${parent}_${suffix}_wheel_visual_geom">
          <mesh filename="pr2_wheel.stlb" />
        </geometry>
      </visual>
      <collision name="${parent}_${suffix}_wheel_collision">
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry name="${parent}_${suffix}_wheel_collision_geom">
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
      </collision>
    </link>


    <gazebo name="${parent}_${suffix}_wheel_sensor" reference="${parent}_${suffix}_wheel_link">
      <sensor:contact name="${parent}_${suffix}_wheel_contact_sensor">
        <geom>${parent}_${suffix}_wheel_collision</geom>
        <updateRate>100.0</updateRate>
        <controller:ros_bumper name="${parent}_${suffix}_wheel_ros_bumper_controller" plugin="libros_bumper.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>100.0</updateRate>
          <bumperTopicName>${parent}_${suffix}_wheel_bumper</bumperTopicName>
          <interface:bumper name="${parent}_${suffix}_wheel_ros_bumper_iface" />
        </controller:ros_bumper>
      </sensor:contact>
    </gazebo>
    <gazebo name="friction_coefficients" reference="${parent}_${suffix}_wheel_collision">
      <mu1 value="100.0" />
      <mu2 value="100.0" />
      <kp  value="1000000.0" />
      <kd  value="1.0" />
    </gazebo>

    <ogre name="${parent}_${suffix}_wheel_visual_mesh" reference="${parent}_${suffix}_wheel_visual">
      <mesh value="pr2_wheel.mesh" />
    </ogre>
    <ogre name="gazebo_material" reference="${parent}_${suffix}_wheel_visual">
      <!-- TODO should be different for left and right wheel-->
      <material value="PR2/${parent}_${suffix}_wheel_link" />
    </ogre>

    <transmission type="SimpleTransmission" name="${parent}_${suffix}_wheel_trans">
      <actuator name="${parent}_${suffix}_wheel_motor_alpha2" />
      <joint name="${parent}_${suffix}_wheel_joint" />
      <mechanicalReduction>${-1 * reflect * 79.226}</mechanicalReduction>
      <calibration values="1.5 -1" />
    </transmission>
  </macro>

  <macro name="pr2_caster_alpha2" params="suffix parent *origin ref_position">

    <link name="${suffix}_caster_rotation_link">
      <joint name="${suffix}_caster_rotation_joint" type="revolute">
        <origin xyz="0 0 0" rpy="0 0 0 0"/>
        <axis xyz="0 0 1" />
        <limit effort="100" velocity="100"/>
        <safety_controller  k_velocity="10" />
        <joint_properties damping="0.0" friction="0.0" />
        <parent name="${parent}">
          <insert_block name="origin" />
        </parent>
      </joint>

      <inertial>
        <mass value="3.473082"/>
        <origin xyz="0 0 0.07" />
        <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                  iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
      </inertial>

      <visual name="${suffix}_caster_rotation_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${suffix}_caster_rotation_visual_geom">
          <mesh filename="caster.stlb" />
        </geometry>
      </visual>

      <collision name="${suffix}_caster_rotation_collision">
        <origin xyz="0 0 0.07" rpy="0.0 0.0 0.0" />
        <geometry name="${suffix}_caster_rotation_collision_geom">
          <box size="0.192 0.164 0.013" />
        </geometry>
      </collision>
    </link>


    <ogre name="${suffix}_caster_rotation_visual_mesh" reference="${suffix}_caster_rotation_visual">
      <elem key="mesh" value="caster.mesh" />
    </ogre>
    <ogre name="gazebo_material" reference="${suffix}_caster_rotation_visual">
      <elem key="material" value="PR2/Green" />
    </ogre>

    <transmission type="SimpleTransmission" name="${suffix}_caster_rotation_trans">
      <actuator name="${suffix}_caster_rotation_motor_alpha2" />
      <joint name="${suffix}_caster_rotation_joint" />
      <mechanicalReduction>79.226</mechanicalReduction>
      <calibration reference_position="${ref_position}" values="1.5 -1" />
    </transmission>

    <!-- Double check these are right for the Alpha 2.0's -->
    <pr2_wheel_alpha2 parent="${suffix}_caster" suffix="l" reflect="1" />
    <pr2_wheel_alpha2 parent="${suffix}_caster" suffix="r" reflect="-1" />
  </macro>


  <macro name="pr2_base_alpha2" params="name *origin">


    <link name="${name}_link">
      <joint name="${name}_joint" type="planar">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent name="world">
          <insert_block name="origin" />
        </parent>
      </joint>

      <inertial>
        <mass value="${base_mass}" />
        <origin xyz="${base_cg_x} ${base_cg_y} ${base_cg_z}" />
        <inertia ixx="5.652232699207" ixy="-0.009719934438" ixz="1.293988226423"
                 iyy="5.669473158652" iyz="-0.007379583694" izz="3.683196351726" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="0 0 ${base_height_offset}" rpy="0 0 0" />
        <geometry name="${name}_visual_geom">
          <mesh filename="base.stlb" />
        </geometry>
      </visual>

      <collision name="${name}_collision">
        <origin xyz="0 0 ${base_height_offset+base_size_z/2}" rpy="0 0 0" />
        <geometry name="${name}_collision_geom">
          <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
        </geometry>
      </collision>
    </link>


    <gazebo name="bumper_sensor" reference="${name}_link">
      <sensor:contact name="${name}_contact_sensor">
        <geom>${name}_collision</geom>
        <updateRate>100.0</updateRate>
        <controller:ros_bumper name="${name}_ros_bumper_controller" plugin="libros_bumper.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>100.0</updateRate>
          <bumperTopicName>${name}_bumper</bumperTopicName>
          <interface:bumper name="${name}_bumper_iface" />
        </controller:ros_bumper>
      </sensor:contact>
    </gazebo>
    <gazebo name="gazebo_material" reference="${name}_visual">
      <material value="PR2/Green" />
    </gazebo>

    <ogre name="${name}_visual_mesh" reference="${name}_visual" >
      <mesh value="base.mesh" />
    </ogre>

    <!-- base laser -->
    <link name="base_laser" type="laser">

      <joint name="base_laser_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <parent name="${name}_link">
          <origin xyz="${base_laser_x} ${base_laser_y} ${base_height_offset+base_laser_z}" rpy="0 0 0" />
        </parent>
      </joint>

      <inertial>
        <mass value="1.0" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
      </inertial>

      <visual name="base_lvisual">
        <origin xyz="0 0 ${base_laser_collision_offset_z}" rpy="0 0 0" />
        <geometry name="base_laser_visual_geom">
          <box size="${base_laser_size_x} ${base_laser_size_y} ${base_laser_size_z}"/>
        </geometry>
      </visual>

      <collision name="base_lcollision">
        <origin xyz="0 0 ${base_laser_collision_offset_z}" rpy="0 0 0" />
        <geometry name="base_laser_collision_geom">
          <box size="${base_laser_size_x} ${base_laser_size_y} ${base_laser_size_z}"/>
        </geometry>
      </collision>

    </link>


    <gazebo name="sensor" reference="base_laser">
      <sensor:ray name="base_laser">
        <rayCount>640</rayCount>
        <rangeCount>640</rangeCount>
        <laserCount>1</laserCount>
        <origin>0.0 0.0 0.0</origin>
        <displayRays>false</displayRays>

        <minAngle>-100</minAngle> <!-- scans own arms if -135~+135 -->
        <maxAngle>100</maxAngle>

        <minRange>0.05</minRange>
        <maxRange>10.0</maxRange>
        <resRange>0.01</resRange>
        <updateRate>20.0</updateRate>
        <controller:ros_laser name="ros_base_laser_controller" plugin="libros_laser.so">
          <gaussianNoise>0.005</gaussianNoise>
          <alwaysOn>true</alwaysOn>
          <updateRate>20.0</updateRate>
          <topicName>base_scan</topicName>
          <frameName>base_laser</frameName>
          <interface:laser name="ros_base_laser_iface" />
        </controller:ros_laser>
      </sensor:ray>
    </gazebo>
    <gazebo name="gazebo_material" reference="base_lvisual">
      <material value="PR2/Red" />
    </gazebo>
    <gazebo name="sensor" reference="${name}_link">
      <controller:ros_p3d name="p3d_base_controller" plugin="libros_p3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>100.0</updateRate>
        <bodyName>base_link</bodyName>
        <topicName>base_pose_ground_truth</topicName>
        <gaussianNoise>0.01</gaussianNoise>
        <frameName>map</frameName>
        <xyzOffsets>25.7 25.7 0</xyzOffsets> <!-- initialize odometry for fake localization-->
        <rpyOffsets>0 0 0</rpyOffsets>
        <interface:position name="p3d_base_position"/>
      </controller:ros_p3d>
    </gazebo>

    <!-- all four caster macros -->
    <pr2_caster_alpha2 suffix="fl" parent="${name}_link" ref_position="${cal_caster_fl}" >
      <origin xyz="${caster_offset_x} ${caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
    </pr2_caster_alpha2>
    <pr2_caster_alpha2 suffix="fr" parent="${name}_link" ref_position="${cal_caster_fr}" >
      <origin xyz="${caster_offset_x} ${-caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
    </pr2_caster_alpha2>
    <pr2_caster_alpha2 suffix="bl" parent="${name}_link" ref_position="${cal_caster_bl}" >
      <origin xyz="${-caster_offset_x} ${caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
    </pr2_caster_alpha2>
    <pr2_caster_alpha2 suffix="br" parent="${name}_link" ref_position="${cal_caster_br}"  >
      <origin xyz="${-caster_offset_x} ${-caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
    </pr2_caster_alpha2>

  </macro>

  <property name="caster_offset_x" value="0.2225" />
  <property name="caster_offset_y" value="0.2225" />
  <property name="caster_offset_z" value="0.0282" />

  <macro name="pr2_base" params="name *origin">


    <link name="${name}_link">
      <joint name="${name}_joint" type="planar">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent name="world">
          <insert_block name="origin" />
        </parent>
      </joint>

      <inertial>
        <mass value="${base_mass}" />
        <origin xyz="${base_cg_x} ${base_cg_y} ${base_cg_z}" />
        <inertia ixx="5.652232699207" ixy="-0.009719934438" ixz="1.293988226423"
                 iyy="5.669473158652" iyz="-0.007379583694" izz="3.683196351726" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="0 0 ${base_height_offset}" rpy="0 0 0" />
        <geometry name="${name}_visual_geom">
          <mesh filename="base.stlb" />
        </geometry>
      </visual>

      <collision name="${name}_collision">
        <origin xyz="0 0 ${base_height_offset+base_size_z/2}" rpy="0 0 0" />
        <geometry name="${name}_collision_geom">
          <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
        </geometry>
      </collision>
    </link>


    <gazebo name="bumper_sensor" reference="${name}_link">
      <sensor:contact name="${name}_contact_sensor">
        <geom>${name}_collision</geom>
        <updateRate>100.0</updateRate>
        <controller:ros_bumper name="${name}_ros_bumper_controller" plugin="libros_bumper.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>100.0</updateRate>
          <bumperTopicName>${name}_bumper</bumperTopicName>
          <interface:bumper name="${name}_bumper_iface" />
        </controller:ros_bumper>
      </sensor:contact>
    </gazebo>
    <gazebo name="base_collision_properties" reference="${name}_collision">
      <mu1 value="500.0" />
      <mu2 value="500.0" />
      <kp  value="100000000.0" />
      <kd  value="1.0" />
    </gazebo>
    <gazebo name="gazebo_material" reference="${name}_visual">
      <material value="PR2/Green" />
    </gazebo>

    <ogre name="${name}_visual_mesh" reference="${name}_visual">
      <mesh value="base.mesh" />
    </ogre>

    <!-- base laser -->
    <link name="base_laser" type="laser">
      <joint name="base_laser_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <parent name="${name}_link" />
          <origin xyz="${base_laser_x} ${base_laser_y} ${base_height_offset+base_laser_z}" rpy="0 0 0" />
        </parent>
      </joint>

      <inertial>
        <mass value="1.0" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
      </inertial>

      <visual name="base_lvisual">
        <origin xyz="0 0 ${base_laser_collision_offset_z}" rpy="0 0 0" />
        <geometry name="base_laser_visual_geom">
          <box size="${base_laser_size_x} ${base_laser_size_y} ${base_laser_size_z}"/>
        </geometry>
      </visual>

      <collision name="base_lcollision">
        <origin xyz="0 0 ${base_laser_collision_offset_z}" rpy="0 0 0" />
        <geometry name="base_laser_collision_geom">
          <box size="${base_laser_size_x} ${base_laser_size_y} ${base_laser_size_z}"/>
        </geometry>
      </collision>

    </link>


    <gazebo name="sensor" reference="base_laser">
      <sensor:ray name="base_laser">
        <rayCount>640</rayCount>
        <rangeCount>640</rangeCount>
        <laserCount>1</laserCount>
        <origin>0.0 0.0 0.0</origin>
        <displayRays>false</displayRays>

        <minAngle>-100</minAngle> <!-- scans own arms if -135~+135 -->
        <maxAngle>100</maxAngle>

        <minRange>0.05</minRange>
        <maxRange>10.0</maxRange>
        <resRange>0.01</resRange>
        <updateRate>20.0</updateRate>
        <controller:ros_laser name="ros_base_laser_controller" plugin="libros_laser.so">
          <gaussianNoise>0.005</gaussianNoise>
          <alwaysOn>true</alwaysOn>
          <updateRate>20.0</updateRate>
          <topicName>base_scan</topicName>
          <frameName>base_laser</frameName>
          <interface:laser name="ros_base_laser_iface" />
        </controller:ros_laser>
      </sensor:ray>
    </gazebo>
    <gazebo name="gazebo_material" reference="base_lvisual">
      <material value="PR2/Red" />
    </gazebo>

    <!-- modeling plug on base holder magnet location -->
    <link name="plug_magnet" type="laser">

      <joint name="plug_magnet_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <anchor xyz="0 0 0" />
        <parent name="${name}_link" />
          <origin xyz="0.18 0 ${base_height_offset+0.235}" rpy="0 0 0" />
        </parent>
      </joint>

      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0.0" />
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
      </inertial>

      <visual name="plug_mavisual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="plug_magnet_visual_geom">
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </visual>

      <collision name="plug_macollision">
        <origin xyz="0 0 0.0" rpy="0 0 0" />
        <geometry name="plug_magnet_collision_geom">
          <box size=".001 .001 .001" />
        </geometry>
      </collision>

    </link>
    <gazebo name="gazebo_material" reference="plug_mavisual">
      <material value="PR2/Red" />
    </gazebo>
    <gazebo name="sensor" reference="plug_magnet">
      <controller:ros_p3d name="p3d_plug_magnet_controller" plugin="libros_p3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>100.0</updateRate>
        <bodyName>plug_magnet</bodyName>
        <topicName>plug_magnet_pose_ground_truth</topicName>
        <gaussianNoise>0.01</gaussianNoise>
        <frameName>map</frameName>
        <xyzOffsets>0 0 0</xyzOffsets> <!-- initialize odometry for fake localization-->
        <rpyOffsets>0 0 0</rpyOffsets>
        <interface:position name="p3d_plug_magnet_position"/>
      </controller:ros_p3d>
    </gazebo>
    <gazebo name="sensor" reference="${name}_link">
      <controller:ros_p3d name="p3d_base_controller" plugin="libros_p3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>100.0</updateRate>
        <bodyName>base_link</bodyName>
        <topicName>base_pose_ground_truth</topicName>
        <gaussianNoise>0.01</gaussianNoise>
        <frameName>map</frameName>
        <xyzOffsets>25.7 25.7 0</xyzOffsets> <!-- initialize odometry for fake localization-->
        <rpyOffsets>0 0 0</rpyOffsets>
        <interface:position name="p3d_base_position"/>
      </controller:ros_p3d>
    </gazebo>


    <pr2_caster suffix="fl" parent="${name}_link">
      <origin xyz="${caster_offset_x} ${caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
    </pr2_caster>
    <pr2_caster suffix="fr" parent="${name}_link">
      <origin xyz="${caster_offset_x} ${-caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
    </pr2_caster>
    <pr2_caster suffix="bl" parent="${name}_link">
      <origin xyz="${-caster_offset_x} ${caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
    </pr2_caster>
    <pr2_caster suffix="br" parent="${name}_link">
      <origin xyz="${-caster_offset_x} ${-caster_offset_y} ${caster_offset_z}" rpy="0 0 0" />
    </pr2_caster>

  </macro>



  <!--                    Calibration                            -->

  <macro name="caster_calibrator" params="suffix">
    <controller type="CasterCalibrationControllerNode"
                name="cal_caster_${suffix}" topic="cal_caster_${suffix}">
      <calibrate joint="${suffix}_caster_rotation_joint"
                 actuator="${suffix}_caster_rotation_motor"
                 transmission="${suffix}_caster_rotation_trans"
                 velocity="2.0" />
      <joints caster="${suffix}_caster_rotation_joint"
              wheel_l="${suffix}_caster_l_wheel_joint"
              wheel_r="${suffix}_caster_r_wheel_joint" />
      <caster_pid p="6" i="0" d="0" iClamp="0" />
      <wheel_pid p="4" i="0" d="0" iClamp="0" />
    </controller>
  </macro>

  <macro name="caster_calibrator_alpha2" params="suffix">
    <controller type="CasterCalibrationControllerNode"
                name="cal_caster_${suffix}" topic="cal_caster_${suffix}">
      <calibrate joint="${suffix}_caster_rotation_joint"
                 actuator="${suffix}_caster_rotation_motor_alpha2"
                 transmission="${suffix}_caster_rotation_trans"
                 velocity="1.0" />
      <joints caster="${suffix}_caster_rotation_joint"
              wheel_l="${suffix}_caster_l_wheel_joint"
              wheel_r="${suffix}_caster_r_wheel_joint" />
      <caster_pid p="6" i="0" d="0" iClamp="0" />
      <wheel_pid p="6" i="0" d="0" iClamp="0" />
    </controller>
  </macro>

  <macro name="base_calibrator_alpha2">
    <caster_calibrator_alpha2 suffix="fl" />
    <caster_calibrator_alpha2 suffix="fr" />
    <caster_calibrator_alpha2 suffix="bl" />
    <caster_calibrator_alpha2 suffix="br" />
  </macro>


  <macro name="base_calibrator">
    <caster_calibrator suffix="fl" />
    <caster_calibrator suffix="fr" />
    <caster_calibrator suffix="bl" />
    <caster_calibrator suffix="br" />
  </macro>


</robot>
