<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

  <!-- base appears "raised" from our initial geom def from function -->
  <property name="base_height_offset" value="0.05" />

  <!-- simplified box collision geometry for hokuyo laser -->
  <property name="base_laser_x" value="0.275" />
  <property name="base_laser_y" value="0.0" />
  <property name="base_laser_z" value="0.252" />
  <property name="base_laser_size_x" value="0.08" />
  <property name="base_laser_size_y" value="0.08" />
  <property name="base_laser_size_z" value="0.03" />
  <property name="base_laser_collision_offset_z" value="0.03" />

  <macro name="pr2_wheel_ext" params="suffix parent reflect">

    <gazebo name="${parent}_${suffix}_wheel_sensor" reference="${parent}_${suffix}_wheel_link">
      <sensor:contact name="${parent}_${suffix}_wheel_contact_sensor">
        <geom>${parent}_${suffix}_wheel_collision</geom>
        <updateRate>100.0</updateRate>
        <controller:ros_bumper name="${parent}_${suffix}_wheel_ros_bumper_controller" plugin="libros_bumper.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>100.0</updateRate>
          <bumperTopicName>${parent}_${suffix}_wheel_bumper</bumperTopicName>
          <interface:bumper name="${parent}_${suffix}_wheel_ros_bumper_iface" />
        </controller:ros_bumper>
      </sensor:contact>
    </gazebo>
    <gazebo name="friction_coefficients" reference="${parent}_${suffix}_wheel_collision">
      <mu1 value="100.0" />
      <mu2 value="100.0" />
      <kp  value="1000000.0" />
      <kd  value="1.0" />
    </gazebo>

    <ogre name="${parent}_${suffix}_wheel_visual_mesh" reference="${parent}_${suffix}_wheel_visual">
      <mesh value="$(find pr2_ogre)/Media/models/pr2_wheel.mesh" />
    </ogre>
    <ogre name="gazebo_material" reference="${parent}_${suffix}_wheel_visual">
      <!-- TODO should be different for left and right wheel-->
      <material value="PR2/${parent}_${suffix}_wheel_link" />
    </ogre>

    <transmission type="SimpleTransmission" name="${parent}_${suffix}_wheel_trans">
      <actuator name="${parent}_${suffix}_wheel_motor" />
      <joint name="${parent}_${suffix}_wheel_joint" />
      <mechanicalReduction>${reflect*75.05}</mechanicalReduction>
    </transmission>
  </macro>

  <macro name="pr2_caster_ext" params="suffix parent *origin">

    <ogre name="${suffix}_caster_rotation_visual_mesh" reference="${suffix}_caster_rotation_visual">
      <elem key="mesh" value="$(find pr2_ogre)/Media/models/caster.mesh" />
    </ogre>
    <ogre name="gazebo_material" reference="${suffix}_caster_rotation_visual">
      <elem key="material" value="PR2/Green" />
    </ogre>

    <transmission type="SimpleTransmission" name="${suffix}_caster_rotation_trans">
      <actuator name="${suffix}_caster_rotation_motor" />
      <joint name="${suffix}_caster_rotation_joint" />
      <mechanicalReduction>-75.05</mechanicalReduction>
    </transmission>

  </macro>

  <!--                                                      -->
  <!-- Alpha 2.0 hardware                                   -->
  <!--                                                      -->
  <macro name="pr2_wheel_alpha2_ext" params="suffix parent reflect">

    <gazebo name="${parent}_${suffix}_wheel_sensor" reference="${parent}_${suffix}_wheel_link">
      <sensor:contact name="${parent}_${suffix}_wheel_contact_sensor">
        <geom>${parent}_${suffix}_wheel_collision</geom>
        <updateRate>100.0</updateRate>
        <controller:ros_bumper name="${parent}_${suffix}_wheel_ros_bumper_controller" plugin="libros_bumper.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>100.0</updateRate>
          <bumperTopicName>${parent}_${suffix}_wheel_bumper</bumperTopicName>
          <interface:bumper name="${parent}_${suffix}_wheel_ros_bumper_iface" />
        </controller:ros_bumper>
      </sensor:contact>
    </gazebo>
    <gazebo name="friction_coefficients" reference="${parent}_${suffix}_wheel_collision">
      <mu1 value="100.0" />
      <mu2 value="100.0" />
      <kp  value="1000000.0" />
      <kd  value="1.0" />
    </gazebo>

    <ogre name="${parent}_${suffix}_wheel_visual_mesh" reference="${parent}_${suffix}_wheel_visual">
      <mesh value="$(find pr2_ogre)/Media/models/pr2_wheel.mesh" />
    </ogre>
    <ogre name="gazebo_material" reference="${parent}_${suffix}_wheel_visual">
      <!-- TODO should be different for left and right wheel-->
      <material value="PR2/${parent}_${suffix}_wheel_link" />
    </ogre>

    <transmission type="SimpleTransmission" name="${parent}_${suffix}_wheel_trans">
      <actuator name="${parent}_${suffix}_wheel_motor_alpha2" />
      <joint name="${parent}_${suffix}_wheel_joint" />
      <mechanicalReduction>${-1 * reflect * 79.226}</mechanicalReduction>
    </transmission>
  </macro>

  <macro name="pr2_caster_alpha2_ext" params="suffix parent *origin ref_position">

    <ogre name="${suffix}_caster_rotation_visual_mesh" reference="${suffix}_caster_rotation_visual">
      <elem key="mesh" value="$(find pr2_ogre)/Media/models/caster.mesh" />
    </ogre>
    <ogre name="gazebo_material" reference="${suffix}_caster_rotation_visual">
      <elem key="material" value="PR2/Green" />
    </ogre>

    <transmission type="SimpleTransmission" name="${suffix}_caster_rotation_trans">
      <actuator name="${suffix}_caster_rotation_motor_alpha2" />
      <joint name="${suffix}_caster_rotation_joint" />
      <mechanicalReduction>79.226</mechanicalReduction>
    </transmission>

    <!-- Double check these are right for the Alpha 2.0's -->
    <pr2_wheel_alpha2 parent="${suffix}_caster" suffix="l" reflect="1" />
    <pr2_wheel_alpha2 parent="${suffix}_caster" suffix="r" reflect="-1" />
  </macro>


  <macro name="pr2_base_alpha2_ext" params="name *origin">

    <gazebo name="bumper_sensor" reference="${name}_link">
      <sensor:contact name="${name}_contact_sensor">
        <geom>${name}_collision</geom>
        <updateRate>100.0</updateRate>
        <controller:ros_bumper name="${name}_ros_bumper_controller" plugin="libros_bumper.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>100.0</updateRate>
          <bumperTopicName>${name}_bumper</bumperTopicName>
          <interface:bumper name="${name}_bumper_iface" />
        </controller:ros_bumper>
      </sensor:contact>
    </gazebo>
    <gazebo name="gazebo_material" reference="${name}_visual">
      <material value="PR2/Green" />
    </gazebo>

    <ogre name="${name}_visual_mesh" reference="${name}_visual" >
      <mesh value="$(find pr2_ogre)/Media/models/base.mesh" />
    </ogre>

    <!-- base laser -->
    <link name="base_laser" type="laser">

      <joint name="base_laser_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <parent name="${name}_link">
          <origin xyz="${base_laser_x} ${base_laser_y} ${base_height_offset+base_laser_z}" rpy="0 0 0" />
        </parent>
      </joint>

      <inertial>
        <mass value="1.0" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
      </inertial>

      <visual name="base_lvisual">
        <origin xyz="0 0 ${base_laser_collision_offset_z}" rpy="0 0 0" />
        <geometry name="base_laser_visual_geom">
          <box size="${base_laser_size_x} ${base_laser_size_y} ${base_laser_size_z}"/>
        </geometry>
      </visual>

      <collision name="base_lcollision">
        <origin xyz="0 0 ${base_laser_collision_offset_z}" rpy="0 0 0" />
        <geometry name="base_laser_collision_geom">
          <box size="${base_laser_size_x} ${base_laser_size_y} ${base_laser_size_z}"/>
        </geometry>
      </collision>

    </link>


    <gazebo name="sensor" reference="base_laser">
      <sensor:ray name="base_laser">
        <rayCount>640</rayCount>
        <rangeCount>640</rangeCount>
        <laserCount>1</laserCount>
        <origin>0.0 0.0 0.0</origin>
        <displayRays>false</displayRays>

        <minAngle>-100</minAngle> <!-- scans own arms if -135~+135 -->
        <maxAngle>100</maxAngle>

        <minRange>0.05</minRange>
        <maxRange>10.0</maxRange>
        <resRange>0.01</resRange>
        <updateRate>20.0</updateRate>
        <controller:ros_laser name="ros_base_laser_controller" plugin="libros_laser.so">
          <gaussianNoise>0.005</gaussianNoise>
          <alwaysOn>true</alwaysOn>
          <updateRate>20.0</updateRate>
          <topicName>base_scan</topicName>
          <frameName>base_laser</frameName>
          <interface:laser name="ros_base_laser_iface" />
        </controller:ros_laser>
      </sensor:ray>
    </gazebo>
    <gazebo name="gazebo_material" reference="base_lvisual">
      <material value="PR2/Red" />
    </gazebo>
    <gazebo name="sensor" reference="${name}_link">
      <controller:ros_p3d name="p3d_base_controller" plugin="libros_p3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>100.0</updateRate>
        <bodyName>base_link</bodyName>
        <topicName>base_pose_ground_truth</topicName>
        <gaussianNoise>0.01</gaussianNoise>
        <frameName>map</frameName>
        <xyzOffsets>25.7 25.7 0</xyzOffsets> <!-- initialize odometry for fake localization-->
        <rpyOffsets>0 0 0</rpyOffsets>
        <interface:position name="p3d_base_position"/>
      </controller:ros_p3d>
    </gazebo>

  </macro>

  <property name="caster_offset_x" value="0.2225" />
  <property name="caster_offset_y" value="0.2225" />
  <property name="caster_offset_z" value="0.0282" />

  <macro name="pr2_base_ext" params="name *origin">

    <gazebo name="bumper_sensor" reference="${name}_link">
      <sensor:contact name="${name}_contact_sensor">
        <geom>${name}_collision</geom>
        <updateRate>100.0</updateRate>
        <controller:ros_bumper name="${name}_ros_bumper_controller" plugin="libros_bumper.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>100.0</updateRate>
          <bumperTopicName>${name}_bumper</bumperTopicName>
          <interface:bumper name="${name}_bumper_iface" />
        </controller:ros_bumper>
      </sensor:contact>
    </gazebo>
    <gazebo name="base_collision_properties" reference="${name}_collision">
      <mu1 value="500.0" />
      <mu2 value="500.0" />
      <kp  value="100000000.0" />
      <kd  value="1.0" />
    </gazebo>
    <gazebo name="gazebo_material" reference="${name}_visual">
      <material value="PR2/Green" />
    </gazebo>

    <ogre name="${name}_visual_mesh" reference="${name}_visual">
      <mesh value="$(find pr2_ogre)/Media/models/base.mesh" />
    </ogre>

    <!-- base laser -->

    <gazebo name="sensor" reference="base_laser">
      <sensor:ray name="base_laser">
        <rayCount>640</rayCount>
        <rangeCount>640</rangeCount>
        <laserCount>1</laserCount>
        <origin>0.0 0.0 0.0</origin>
        <displayRays>false</displayRays>

        <minAngle>-100</minAngle> <!-- scans own arms if -135~+135 -->
        <maxAngle>100</maxAngle>

        <minRange>0.05</minRange>
        <maxRange>10.0</maxRange>
        <resRange>0.01</resRange>
        <updateRate>20.0</updateRate>
        <controller:ros_laser name="ros_base_laser_controller" plugin="libros_laser.so">
          <gaussianNoise>0.005</gaussianNoise>
          <alwaysOn>true</alwaysOn>
          <updateRate>20.0</updateRate>
          <topicName>base_scan</topicName>
          <frameName>base_laser</frameName>
          <interface:laser name="ros_base_laser_iface" />
        </controller:ros_laser>
      </sensor:ray>
    </gazebo>
    <gazebo name="gazebo_material" reference="base_lvisual">
      <material value="PR2/Red" />
    </gazebo>

    <!-- modeling plug on base holder magnet location -->

    <gazebo name="gazebo_material" reference="plug_mavisual">
      <material value="PR2/Red" />
    </gazebo>
    <gazebo name="sensor" reference="plug_magnet">
      <controller:ros_p3d name="p3d_plug_magnet_controller" plugin="libros_p3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>100.0</updateRate>
        <bodyName>plug_magnet</bodyName>
        <topicName>plug_magnet_pose_ground_truth</topicName>
        <gaussianNoise>0.01</gaussianNoise>
        <frameName>map</frameName>
        <xyzOffsets>0 0 0</xyzOffsets> <!-- initialize odometry for fake localization-->
        <rpyOffsets>0 0 0</rpyOffsets>
        <interface:position name="p3d_plug_magnet_position"/>
      </controller:ros_p3d>
    </gazebo>
    <gazebo name="sensor" reference="${name}_link">
      <controller:ros_p3d name="p3d_base_controller" plugin="libros_p3d.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>100.0</updateRate>
        <bodyName>base_link</bodyName>
        <topicName>base_pose_ground_truth</topicName>
        <gaussianNoise>0.01</gaussianNoise>
        <frameName>map</frameName>
        <xyzOffsets>25.7 25.7 0</xyzOffsets> <!-- initialize odometry for fake localization-->
        <rpyOffsets>0 0 0</rpyOffsets>
        <interface:position name="p3d_base_position"/>
      </controller:ros_p3d>
    </gazebo>


  </macro>




</robot>
