<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

  <property name="M_PI" value="3.1415926535897931" />

  <macro name="pr2_tilting_laser" params="name parent *origin">

    <link name="${name}_mount_link">
      <joint name="${name}_mount_joint" type="revolute">
        <axis xyz="0 1 0" />
        <anchor xyz="0 0 0" />
        <limit min="-0.785" max="1.57" effort="0.5292" velocity="100" />
        <safety_controller k_position="100" k_velocity="0.05" lower="${-0.785+0.0}" upper="${1.57-0.0}" />
        <joint_properties damping="0.008" />
        <parent name="${parent}">
          <insert_block name="origin" />
        </parent>
      </joint>

      <inertial>
        <mass value="0.05" />
        <origin xyz="-0.03 0 -0.03" rpy="0 0 0" />
        <inertia ixx="0.0001" ixy="0" ixz="0" 
                 iyy="0.00001" iyz="0" 
                 izz="0.0001" />
      </inertial>

      <visual name="${name}_mount_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_mount_visual_geom">
          <mesh filename="hok_tilt.stlb" />
        </geometry>
      </visual>

      <collision name="${name}_mount_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_mount_collision_geom" >
          <box size=".001 .001 .001" />
        </geometry>
      </collision>
    </link>

    <gazebo name="gazebo_material" reference="${name}_mount_visual">
      <material value="PR2/Red" />
    </gazebo>
    <ogre name="${name}_mount_visual_mesh" reference="${name}_mount_visual">
      <mesh value="hok_tilt.mesh" />
    </ogre>

    <transmission type="SimpleTransmission" name="${name}_mount_trans">
      <actuator name="${name}_mount_motor" />
      <joint name="${name}_mount_joint" />
      <mechanicalReduction>6.0</mechanicalReduction>
      <calibration reference_position="-0.35" values="0 0" />
    </transmission>

    <link name="${name}_link" type="laser">
      <joint name="${name}_joint" type="fixed">
        <axis xyz="0 1 0" />
        <anchor xyz="0 0 0" />
        <parent name="${name}_mount_link">
          <origin xyz="0 0 0.03" rpy="0 0 0" />
        </parent>
      </joint>

      <inertial>
        <mass value="0.001" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.0001" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_visual_geom">
          <box size="0.001 0.001 0.001" />
        </geometry>
      </visual>

      <collision name="${name}_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_collision_geom" >
          <box size=".001 .001 .001" />
        </geometry>
      </collision>

    </link>

    <gazebo name="sensor" reference="${name}_link">
      <sensor:ray name="${name}">
        <rayCount>640</rayCount>
        <rangeCount>640</rangeCount>
        <laserCount>1</laserCount>

        <origin>0.0 0.0 0.0</origin>
        <displayRays>false</displayRays>

        <minAngle>-80</minAngle>
        <maxAngle> 80</maxAngle>

        <minRange>0.05</minRange>
        <maxRange>10.0</maxRange>
        <resRange>0.01</resRange>
        <updateRate>20.0</updateRate>
        <controller:ros_laser name="ros_${name}_controller" plugin="libros_laser.so">
          <gaussianNoise>0.005</gaussianNoise>
          <alwaysOn>true</alwaysOn>
          <updateRate>20.0</updateRate>
          <topicName>tilt_scan</topicName>
          <frameName>${name}_link</frameName>
          <interface:laser name="ros_${name}_iface" />
        </controller:ros_laser>
      </sensor:ray>
    </gazebo>

  </macro>


  <property name="stereo_size_x" value="0.005" />
  <property name="stereo_size_y" value="0.010" />
  <property name="stereo_size_z" value="0.005" />
  <property name="stereo_center_box_center_offset_x" value="0.00" />
  <property name="stereo_center_box_center_offset_z" value="0.05" />
  <property name="stereo_dx" value="0.00" />
  <property name="stereo_dy" value="-0.09" /> <!-- +y to the left -->
  <property name="stereo_dz" value="0.00" />
  <property name="stereo_rx" value="0.00" />
  <property name="stereo_ry" value="0.00" />
  <property name="stereo_rz" value="0.00" />

  <!-- Made by Kevin for A2 sensor package -->
  <!-- Origin is center mount screw on sensor plate mount -->
  <!-- When mounted properly, should have same origin as head plate frame -->
  <macro name="pr2_head_sensor_package" params="name hd_name stereo_name parent *origin">
    <link name="${name}_link" >
      <joint name="${name}_fixed_joint" type="fixed">
        <parent name="${parent}">
          <insert_block name="origin" />
        </parent>
      </joint>

      <inertial>
        <!-- Needs verification with CAD -->
        <mass value="0.05" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0" izz="0.01" />
      </inertial>

      <!-- Should probably get real visuals here at some point -->
      <visual name="${name}_sensor_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_sensor_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </visual>

      <collision name="${name}_sensor_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_sensor_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
    </link>

    <gazebo name="gazebo_material" reference="${name}_sensor_visual">
      <material value="PR2/Blue" />
    </gazebo>

    <!-- Prosilica Camera -->
    <prosilica_cam name="${hd_name}" parent="${name}_link" >
      <!-- Center of camera is 109mm right of center screw, 35mm up -->
      <!-- Camera is slightly recessed from front, where is camera origin? Lens? -->
      <origin xyz="0 -0.109 0.035" rpy="0 0 0" />        
    </prosilica_cam>

    <!-- Stereocam -->
    <double_stereo_camera name="${stereo_name}" parent="${name}_link" >
      <origin xyz="0.0 0.0 0.003" rpy="0 0 0" />
    </double_stereo_camera>
  </macro>

  <!-- Made by Kevin for double stereo camera for PR-2 Beta. -->
  <!-- Needs calibration verification, and CAD check. -->
  <macro name="double_stereo_camera" params="name parent *origin">
    <!-- Define link to stereo cameras, set origin relative to that -->
    <link name="${name}_link">
      <joint name="${name}_fixed_joint" type="fixed">
        <parent name="${parent}">
          <insert_block name="origin" />
        </parent>
      </joint>

      <inertial>
        <!-- Needs verification with CAD -->
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0" izz="0.01" />
      </inertial>

      <!-- Should probably get real visuals here at some point -->
      <visual name="${name}_double_stereo_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_double_stereo_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </visual>

      <collision name="${name}_double_stereo_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_double_stereo_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
    </link>

    <gazebo name="gazebo_material" reference="${name}_double_stereo_visual">
      <material value="PR2/Blue" />
    </gazebo>
    
    <!-- Wide camera is on robot right (hca1), narrow on left (hca2)? -->
    <!-- 15mm offset from center needs check with CAD -->
    <stereo_camera parent="${name}_link" name="wide_stereo" >
      <origin xyz="0 -0.015 0" rpy="0 0 0" />
    </stereo_camera>

    <stereo_camera parent="${name}_link" name="narrow_stereo" >
      <origin xyz="0 0.015 0" rpy="0 0 0" />
    </stereo_camera>
  </macro>

  <macro name="stereo_camera" params="name parent *origin">
    
    <link name="${name}_link">
      <joint name="${name}_fixed_joint" type="fixed">
        <parent name="${parent}">
          <insert_block name="origin" />
        </parent>
      </joint>
      
      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.00482611007"  ixy="-0.000144683999"  ixz="0.000110076136"
                 iyy="0.005218991412"  iyz="-0.000314239509"  izz="0.008618784925" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="${stereo_center_box_center_offset_x} 0 ${stereo_center_box_center_offset_z}" rpy="0 0 0" />
        <geometry name="${name}_visual_geom">
          <box size="${stereo_size_x} ${stereo_size_y} ${stereo_size_z}" />
        </geometry>
      </visual>

      <collision name="${name}_collision">
        <origin xyz="${stereo_center_box_center_offset_x} 0 ${stereo_center_box_center_offset_z}" rpy="0 0 0" />
        <geometry name="${name}_collision_geom">
          <box size="${stereo_size_x} ${stereo_size_y} ${stereo_size_z}" />
        </geometry>
      </collision>
      
    </link>

    <gazebo name="gazebo_material" reference="${name}_visual">
      <material value="PR2/Blue" />
    </gazebo>

    <link name="${name}_optical_frame" type="camera">
      <joint name="${name}_optical_fixed_joint" type="fixed">
        <parent name="${name}_link">
          <origin xyz="${cal_stereo_x}            ${0.045+cal_stereo_y}   ${.0305+cal_stereo_z}"
                  rpy="${-M_PI/2+cal_stereo_roll} ${0.0+cal_stereo_pitch} ${-M_PI/2+cal_stereo_yaw}" />
        </parent>
      </joint>

      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001"  ixy="0.0"  ixz="0.0"
                 iyy="0.001"  iyz="0.0"
                 izz="0.001" />
      </inertial>

      <visual name="${name}_optical_fixed_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_optical_fixed_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </visual>

      <collision name="${name}_optical_fixed_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_optical_fixed_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>

    </link>

    <gazebo name="gazebo_material" reference="${name}_optical_fixed_visual">
      <material value="PR2/Blue" />
    </gazebo>

    <link name="${name}_l_stereo_camera_frame">
      <joint name="${name}_l_stereo_camera_fixed_joint" type="fixed">
        <parent name="${name}_optical_frame">
          <origin xyz="0 0 0" rpy="0 ${-M_PI/2} ${M_PI/2}" />
        </parent>
      </joint>
      
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001" ixy="0.000"  ixz="0.000"
                 iyy="0.001" iyz="0.000"
                 izz="0.001" />
      </inertial>

      <visual name="${name}_l_stereo_camera_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_l_stereo_camera_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </visual>

      <collision name="${name}_l_stereo_camera_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_l_stereo_camera_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
      
    </link>

    <gazebo name="sensor" reference="${name}_l_stereo_camera_frame">
      <sensor:camera name="${name}_l_sensor">
        <imageSize>640 480</imageSize>
        <imageFormat>L8</imageFormat>
        <hfov>90</hfov>
        <nearClip>0.1</nearClip>
        <farClip>100</farClip>
        <updateRate>20.0</updateRate>
        <controller:ros_camera name="${name}_l_controller" plugin="libros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>20.0</updateRate>
          <topicName>${name}/left_image</topicName>
          <frameName>${name}_l_stereo_camera_frame</frameName>
          <interface:camera name="${name}_l_iface" />
        </controller:ros_camera>
      </sensor:camera>
    </gazebo>
    <gazebo name="gazebo_material" reference="${name}_l_stereo_camera_visual">
      <material value="PR2/Blue" />
    </gazebo>

    <link name="${name}_r_stereo_camera_frame">
      <joint name="${name}_r_stereo_camera_fixed_joint" type="fixed">
        <parent name="${name}_l_stereo_camera_frame">
          <origin xyz="${stereo_dx} ${stereo_dy} ${stereo_dz}"
                  rpy="${stereo_rx} ${stereo_ry} ${stereo_rz}" />
        </parent>
      </joint>
      
      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001" ixy="0.000"  ixz="0.000"
                 iyy="0.001" iyz="0.000"
                 izz="0.001" />
      </inertial>

      <visual name="${name}_r_stereo_camera_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_r_stereo_camera_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </visual>

      <collision name="${name}_r_stereo_camera_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_r_stereo_camera_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
      
    </link>

    <gazebo name="sensor" reference="${name}_r_stereo_camera_frame">
      <sensor:camera name="${name}_r_sensor">
        <imageSize>640 480</imageSize>
        <imageFormat>L8</imageFormat>
        <hfov>90</hfov>
        <nearClip>0.1</nearClip>
        <farClip>100</farClip>
        <updateRate>20.0</updateRate>
        <controller:ros_camera name="${name}_r_controller" plugin="libros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>20.0</updateRate>
          <topicName>${name}/right_image</topicName>
          <frameName>${name}_r_stereo_camera_frame</frameName>
          <interface:camera name="${name}_r_iface" />
        </controller:ros_camera>
      </sensor:camera>
    </gazebo>
    <gazebo name="gazebo_material" reference="${name}_r_stereo_camera_visual">
      <material value="PR2/Blue" />
    </gazebo>


    <!-- stereo plugin that produces a raw_stereo message
    -->
    <gazebo name="sensor">
      <controller:ros_stereo_camera name="${name}_controller" plugin="libros_stereo_camera.so">
        <alwaysOn>true</alwaysOn>
        <updateRate>20.0</updateRate>
        <leftCamera>${name}_l_sensor</leftCamera>
        <rightCamera>${name}_r_sensor</rightCamera>
        <topicName>${name}/raw_stereo</topicName>
        <frameName>${name}_optical_frame</frameName>
        <CxPrime>320</CxPrime>
        <Cx>320</Cx>
        <Cy>240</Cy>
        <focal_length>320</focal_length> <!-- image_width / (2*tan(hfov_radian /2)) -->
        <distortion_k1>0</distortion_k1>
        <distortion_k2>0</distortion_k2>
        <distortion_k3>0</distortion_k3>
        <distortion_t1>0</distortion_t1>
        <distortion_t2>0</distortion_t2>
        <baseline>${stereo_dy}</baseline> <!-- home pos. of robot has +x forward, +y left -->
        <interface:stereocamera name="${name}_iface" />
      </controller:ros_stereo_camera>
    </gazebo>

  </macro>


  <macro name="pr2_head_pan" params="name parent *origin">

    <link name="${name}_link">
      <joint name="${name}_joint" type="revolute">
        <axis xyz="0 0 1" />
        <limit min="-2.92" max="2.92" effort="2.645" velocity="6" />
        <safety_controller k_velocity="1.5" lower="${-2.92+0.15}" upper="${2.92-0.15}" k_position="100" />
        <joint_properties damping="1.0" />
        <parent name="${parent}">
          <insert_block name="origin" />
        </parent>
      </joint>


      <inertial>
        <mass value="1.611118" />
        <origin xyz="-0.005717  0.010312 -0.029649" rpy="0 0 0" />
        <inertia ixx="0.00482611007"  ixy="-0.000144683999"  ixz="0.000110076136"
                 iyy="0.005218991412"  iyz="-0.000314239509"  izz="0.008618784925" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="0 0 0.0" rpy="0 0 0 " />
        <geometry name="${name}_visual_geom">
          <mesh filename="head_pan.stlb" />
        </geometry>
      </visual>

      <collision name="${name}_collision">
        <origin xyz="-0.005717  0.010312 -0.029649" rpy="0.0 0.0 0.0 " />
        <geometry name="${name}_collision_geom">
          <box size="0.188 0.219 0.137" />
        </geometry>
      </collision>

    </link>

    <gazebo name="gazebo_material" reference="${name}_visual">
      <material value="PR2/Blue" />
    </gazebo>
    <ogre name="${name}_visual_mesh" reference="${name}_visual">
      <mesh value="head_pan.mesh" />
    </ogre>


    <transmission type="SimpleTransmission" name="${name}_trans">
      <actuator name="${name}_motor" />
      <joint name="${name}_joint" />
      <mechanicalReduction>6.0</mechanicalReduction>
      <calibration reference_position="${-2.79+cal_head_pan_flag}" values="0 0" />
    </transmission>

  </macro>



  <macro name="pr2_head_tilt" params="name parent *origin">

    <link name="${name}_link">
      <joint name="${name}_joint" type="revolute">
        <axis xyz="0 1 0" />
        <limit min="-0.55" max="1.047" effort="12.21" velocity="100" />
        <safety_controller k_velocity="1.5" lower="${-0.55+0.02}" upper="${1.047-0.002}" k_position="100" />
        <joint_properties damping="1.0" />
        <parent name="${parent}">
          <insert_block name="origin" />
        </parent>
      </joint>


      <inertial>
        <mass value="1.749727" />
        <origin xyz="0.041935 0.003569 0.028143" rpy="0 0 0" />
        <inertia ixx="0.010602303435"  ixy="-0.000408814235"  ixz="0.00198303894"
                 iyy="0.011874383747"  iyz="0.000197908779"
                 izz="0.005516790626" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="0 0 0" rpy="0.0 0.0 0.0 " />
        <geometry name="${name}_visual_geom">
          <mesh filename="head_tilt.stlb" />
        </geometry>
      </visual>

      <collision name="${name}_collision">
        <origin xyz="0.041935 0.003569 0.028143" rpy="0 0 0" />
        <geometry name="${name}_collision_geom">
          <box size="0.064 0.253 0.181" />
        </geometry>
      </collision>
    </link>

    <gazebo name="gazebo_material" reference="${name}_visual">
      <material value="PR2/Green" />
    </gazebo>
    <ogre name="${name}_visual_mesh" reference="${name}_visual">
      <mesh value="head_tilt.mesh" />
    </ogre>


    <transmission type="SimpleTransmission" name="${name}_trans">
      <actuator name="${name}_motor" />
      <joint name="${name}_joint" />
      <mechanicalReduction>6.0</mechanicalReduction>
      <calibration reference_position="${-0.195+cal_head_tilt_flag}" values="0 0" />
    </transmission>

  </macro>



  <macro name="pr2_head" params="name parent *origin">
    <pr2_head_pan name="${name}_pan" parent="${parent}">
      <insert_block name="origin" />
    </pr2_head_pan>

    <pr2_head_tilt name="${name}_tilt" parent="${name}_pan_link">
      <origin xyz="0.058 0 0" rpy="0 0 0" />
    </pr2_head_tilt>

    <!-- Head plate frame -->
    <link name="${name}_plate_frame">
      <joint name="${name}_plate_fixed_joint" type="fixed">
        <parent name="${name}_tilt_link">
          <origin xyz="0.0232 0 0.0645" rpy="0 0 0" />     
        </parent>
      </joint>

      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001"  ixy="0.0"  ixz="0.0"
                 iyy="0.001"  iyz="0.0"
                 izz="0.001" />
      </inertial>

      <visual name="${name}_plate_frame_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_plate_frame_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </visual>

      <collision name="${name}_plate_frame_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_plate_frame_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
    </link>

    <gazebo name="gazebo_material" reference="${name}_plate_frame_visual">
      <material value="PR2/Blue" />
    </gazebo>
    
  </macro>

  <!-- Alpha 2.0 head -->
  <!-- Different calibration values, effort/position limits and 
       different joint link positions -->
 <macro name="pr2_tilting_laser_alpha2" params="name parent *origin">

    <link name="${name}_mount_link">
      <joint name="${name}_mount_joint" type="revolute">
        <axis xyz="0 1 0" />
        <anchor xyz="0 0 0" />
        <limit min="-0.785" max="1.57" effort="0.5292" velocity="10.0" />
        <safety_controller k_position="100" k_velocity="0.05" lower="${-0.785+0.0}" upper="${1.57-0.0}" />
        <joint_properties damping="1.0" />
        <parent name="${parent}">
          <insert_block name="origin" />
        </parent>
      </joint>

      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001" ixy="0" ixz="0" 
                 iyy="0.001" iyz="0" 
                 izz="0.001" />
      </inertial>

      <visual name="${name}_mount_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_mount_visual_geom">
          <mesh filename="hok_tilt.stlb" />
        </geometry>
      </visual>

      <collision name="${name}_mount_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_mount_collision_geom" >
          <box size=".001 .001 .001" />
        </geometry>
      </collision>
    </link>

    <gazebo name="gazebo_material" reference="${name}_mount_visual">
      <material value="PR2/Red" />
    </gazebo>
    <ogre name="${name}_mount_visual_mesh" reference="${name}_mount_visual">
      <mesh value="hok_tilt.mesh" />
    </ogre>

    <transmission type="SimpleTransmission" name="${name}_mount_trans">
      <actuator name="${name}_mount_motor" />
      <joint name="${name}_mount_joint" />
      <mechanicalReduction>6.0</mechanicalReduction>
      <calibration reference_position="0.0" values="0 0" />
    </transmission>

    <link name="${name}_link" type="laser">
      <joint name="${name}_joint" type="fixed">
        <axis xyz="0 1 0" />
        <anchor xyz="0 0 0" />
        <parent name="${name}_mount_link">
          <origin xyz="0 0 0.03" rpy="0 0 0" />
        </parent>
      </joint>

      <inertial>
        <mass value="0.1" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_visual_geom">
          <box size="0.001 0.001 0.001" />
        </geometry>
      </visual>

      <collision name="${name}_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_collision_geom" >
          <box size=".001 .001 .001" />
        </geometry>
      </collision>


    </link>

    <gazebo name="sensor" reference="${name}_link">
      <sensor:ray name="${name}">
        <rayCount>640</rayCount>
        <rangeCount>640</rangeCount>
        <laserCount>1</laserCount>

        <origin>0.0 0.0 0.0</origin>
        <displayRays>false</displayRays>

        <minAngle>-80</minAngle>
        <maxAngle> 80</maxAngle>

        <minRange>0.05</minRange>
        <maxRange>10.0</maxRange>
        <resRange>0.01</resRange>
        <updateRate>20.0</updateRate>
        <controller:ros_laser name="ros_${name}_controller" plugin="libros_laser.so">
          <gaussianNoise>0.005</gaussianNoise>
          <alwaysOn>true</alwaysOn>
          <updateRate>20.0</updateRate>
          <topicName>tilt_scan</topicName>
          <frameName>${name}_link</frameName>
          <interface:laser name="ros_${name}_iface" />
        </controller:ros_laser>
      </sensor:ray>
    </gazebo>

  </macro>



  <macro name="pr2_head_pan_alpha2" params="name parent *origin">

    <link name="${name}_link">
      <joint name="${name}_joint" type="revolute">
        <axis xyz="0 0 1" />
        <limit min="-2.92" max="2.92" effort="2.645" velocity="6" />
        <safety_controller k_velocity="1.5" lower="${-2.92+0.15}" upper="${2.92-0.15}" k_position="100" />
        <joint_properties damping="1.0" />
        <parent name="${parent}">
          <insert_block name="origin" />
        </parent>
      </joint>


      <inertial>
        <mass value="1.611118" />
        <origin xyz="-0.005717  0.010312 -0.029649" rpy="0 0 0" />
        <inertia ixx="0.00482611007"   ixy="-0.000144683999"  ixz="0.000110076136"
                 iyy="0.005218991412"  iyz="-0.000314239509"  izz="0.008618784925" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="0 0 0.0" rpy="0 0 0 " />
        <geometry name="${name}_visual_geom">
          <mesh filename="head_pan.stlb" />
        </geometry>
      </visual>

      <collision name="${name}_collision">
        <origin xyz="-0.005717  0.010312 -0.029649" rpy="0.0 0.0 0.0 " />
        <geometry name="${name}_collision_geom">
          <box size="0.188 0.219 0.137" />
        </geometry>
      </collision>

    </link>

    <gazebo name="gazebo_material" reference="${name}_visual">
      <material value="PR2/Blue" />
    </gazebo>
    <ogre name="${name}_visual_mesh" reference="${name}_visual">
      <mesh value="head_pan.mesh" />
    </ogre>

    <transmission type="SimpleTransmission" name="${name}_trans">
      <actuator name="${name}_motor" />
      <joint name="${name}_joint" />
      <mechanicalReduction>6.0</mechanicalReduction>
      <calibration reference_position="${0.0+cal_head_pan_flag_alpha2}" values="0 0" />
    </transmission>
  </macro>

  <!-- Reverts to small tilt motor, still has same cal flags and limits -->
  <macro name="pr2_head_tilt_alpha2" params="name parent *origin">

    <link name="${name}_link">
      <joint name="${name}_joint" type="revolute">
        <axis xyz="0 1 0" />
        <limit min="-0.45" max="1.37" effort="12" velocity="5" />
        <safety_controller k_velocity="100" lower="${-0.45+0.02}" upper="${1.37-0.02}" k_position="100" />
        <joint_properties damping="1.0" />
        <parent name="${parent}">
          <insert_block name="origin" />
        </parent>
      </joint>


      <inertial>
        <mass value="1.749727" />
        <origin xyz="0.041935 0.003569 0.028143" rpy="0 0 0" />
        <inertia ixx="0.010602303435"  ixy="-0.000408814235"  ixz="0.00198303894"  iyy="0.011874383747"  iyz="0.000197908779"  izz="0.005516790626" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="0 0 0" rpy="0.0 0.0 0.0 " />
        <geometry name="${name}_visual_geom">
          <mesh filename="head_tilt.stlb" />
        </geometry>
      </visual>

      <collision name="${name}_collision">
        <origin xyz="0.041935 0.003569 0.028143" rpy="0 0 0" />
        <geometry name="${name}_collision_geom">
          <box size="0.064 0.253 0.181" />
        </geometry>
      </collision>
    </link>

    <gazebo name="gazebo_material" reference="${name}_visual">
      <material value="PR2/Green" />
    </gazebo>
    <ogre name="${name}_visual_mesh" reference="${name}_visual">
      <mesh value="head_tilt.mesh" />
    </ogre>

    <transmission type="SimpleTransmission" name="${name}_trans">
      <actuator name="${name}_motor" /> <!-- Alpha 1.0 motor -->
      <joint name="${name}_joint" />
      <mechanicalReduction>6.0</mechanicalReduction>
      <calibration reference_position="${0.0+cal_head_tilt_flag}" values="0 0" />
    </transmission>
  </macro>


<macro name="pr2_head_tilt_alpha2a" params="name parent *origin">
  <!-- Motor must be configured with 148877 motor -->
    <link name="${name}_link">
      <joint name="${name}_joint" type="revolute">
        <axis xyz="0 1 0" />
        <limit min="-0.45" max="1.37" effort="12.0" velocity="5" />
        <safety_controller k_velocity="10" lower="${-0.45+0.02}" upper="${1.37-0.02}" k_position="100" />
        <joint_properties damping="1.0" />
        <parent name="${parent}">
          <insert_block name="origin" />
        </parent>
      </joint>


      <inertial>
        <mass value="1.749727" />
        <origin xyz="0.041935 0.003569 0.028143" rpy="0 0 0" />
        <inertia ixx="0.010602303435"  ixy="-0.000408814235"  ixz="0.00198303894"  iyy="0.011874383747"  iyz="0.000197908779"  izz="0.005516790626" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="0 0 0" rpy="0.0 0.0 0.0" />
        <geometry name="${name}_visual_geom">
          <mesh filename="head_tilt.stlb" />
        </geometry>
      </visual>

      <collision name="${name}_collision">
        <origin xyz="0.041935 0.003569 0.028143" rpy="0 0 0" />
        <geometry name="${name}_collision_geom">
          <box size="0.064 0.253 0.181" />
        </geometry>
      </collision>
    </link>

    <gazebo name="gazebo_material" reference="${name}_visual">
      <material value="PR2/Green" />
    </gazebo>
    <ogre name="${name}_visual_mesh" reference="${name}_visual">
      <mesh value="head_tilt.mesh" />
    </ogre>

    <transmission type="SimpleTransmission" name="${name}_trans">
      <actuator name="${name}_motor_alpha2a" />
      <joint name="${name}_joint" />
      <mechanicalReduction>6.0</mechanicalReduction>
      <calibration reference_position="${0.0+cal_head_tilt_flag_alpha2}" values="0 0" />
    </transmission>
  </macro>

 <macro name="pr2_head_tilt_alpha2b" params="name parent *origin">
    <link name="${name}_link">
      <joint name="${name}_joint" type="revolute">
        <axis xyz="0 1 0" />
        <limit min="-0.45" max="1.37" effort="12.0" velocity="5" />
        <safety_controller k_velocity="10" lower="${-0.45+0.02}" upper="${1.37-0.02}" k_position="100" />
        <joint_properties damping="1.0" />
        <parent name="${parent}">
          <insert_block name="origin" />
        </parent>
      </joint>


      <inertial>
        <mass value="1.749727" />
        <origin xyz="0.041935 0.003569 0.028143" rpy="0 0 0" />
        <inertia ixx="0.010602303435"  ixy="-0.000408814235"  ixz="0.00198303894"
                 iyy="0.011874383747"  iyz="0.000197908779"
                 izz="0.005516790626" />
      </inertial>

      <visual name="${name}_visual">
        <origin xyz="0 0 0" rpy="0.0 0.0 0.0 " />
        <geometry name="${name}_visual_geom">
          <mesh filename="head_tilt.stlb" />
        </geometry>
      </visual>

      <collision name="${name}_collision">
        <origin xyz="0.041935 0.003569 0.028143" rpy="0 0 0" />
        <geometry name="${name}_collision_geom">
          <box size="0.064 0.253 0.181" />
        </geometry>
      </collision>
    </link>

    <gazebo name="gazebo_material" reference="${name}_visual">
      <material value="PR2/Green" />
    </gazebo>
    <ogre name="${name}_visual_mesh" reference="${name}_visual">
      <mesh value="head_tilt.mesh" />
    </ogre>

    <transmission type="SimpleTransmission" name="${name}_trans">
      <!-- Motor must be configured with 310009 motor with large gearhead -->
      <actuator name="${name}_motor_alpha2b" />
      <joint name="${name}_joint" />
      <mechanicalReduction>6.0</mechanicalReduction>
      <calibration reference_position="${0.0+cal_head_tilt_flag_alpha2}" values="0 0" />
    </transmission>
  </macro>

 <macro name="pr2_head_alpha2" params="name parent *origin">
    <pr2_head_pan_alpha2 name="${name}_pan" parent="${parent}">
      <insert_block name="origin" />
    </pr2_head_pan_alpha2>

    <pr2_head_tilt_alpha2 name="${name}_tilt" parent="${name}_pan_link">
      <!-- Tilt axis moves forward on Alpha 2.0 head, pan moves back -->
      <origin xyz="0.068 0 0" rpy="0 0 0" />
    </pr2_head_tilt_alpha2>

    <!-- Head plate frame -->
    <link name="${name}_plate_frame">
      <joint name="${name}_plate_fixed_joint" type="fixed">
        <parent name="${name}_tilt_link">
          <origin xyz="0.0232 0 0.0645" rpy="0 0 0" />
        </parent>
      </joint>

      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001"  ixy="0.0"  ixz="0.0"
                 iyy="0.001"  iyz="0.0"
                 izz="0.001" />
      </inertial>

      <visual name="${name}_plate_frame_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_plate_frame_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </visual>

      <collision name="${name}_plate_frame_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_plate_frame_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
    </link>

    <gazebo name="gazebo_material" reference="${name}_plate_frame_visual">
      <material value="PR2/Blue" />
    </gazebo>
    <ogre name="${name}_plate_frame_collision_mesh" reference="${name}_plate_frame_collision">
      <mesh>unit_box</mesh>
    </ogre>

  </macro>


<!-- Difference between two heads is motors and gearheads -->
  <macro name="pr2_head_alpha2a" params="name parent *origin">
    <pr2_head_pan_alpha2 name="${name}_pan" parent="${parent}">
      <insert_block name="origin" />
    </pr2_head_pan_alpha2>

    <pr2_head_tilt_alpha2a name="${name}_tilt" parent="${name}_pan_link">
      <!-- Head tilt axis moves 1 cm fwd, pan moves 1cm back in A2 -->
      <origin xyz="0.068 0 0" rpy="0 0 0" />
    </pr2_head_tilt_alpha2a>

    <!-- Head plate frame -->
    <link name="${name}_plate_frame">
      <joint name="${name}_plate_fixed_joint" type="fixed">
        <parent name="${name}_tilt_link">
          <origin xyz="0.0232 0 0.0645" rpy="0 0 0" />     
        </parent>
      </joint>

      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001"  ixy="0.0"  ixz="0.0"
                 iyy="0.001"  iyz="0.0"
                 izz="0.001" />
      </inertial>

      <visual name="${name}_plate_frame_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_plate_frame_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </visual>

      <collision name="${name}_plate_frame_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_plate_frame_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
    </link>

    <gazebo name="gazebo_material" reference="${name}_plate_frame_visual">
      <material value="PR2/Blue" />
    </gazebo>
    
  </macro>

 <macro name="pr2_head_alpha2b" params="name parent *origin">
    <pr2_head_pan_alpha2 name="${name}_pan" parent="${parent}">
      <insert_block name="origin" />
    </pr2_head_pan_alpha2>

    <pr2_head_tilt_alpha2b name="${name}_tilt" parent="${name}_pan_link">
      <!-- Head tilt axis moves 1 cm fwd, pan moves 1cm back in A2 -->
      <origin xyz="0.068 0 0" rpy="0 0 0" />
    </pr2_head_tilt_alpha2b>

    <!-- Head plate frame -->
    <link name="${name}_plate_frame">
      <joint name="${name}_plate_fixed_joint" type="fixed">
        <parent name="${name}_tilt_link">
          <origin xyz="0.0232 0 0.0645" rpy="0 0 0" />     
        </parent>
      </joint>

      <inertial>
        <mass value="0.01" />
        <origin xyz="0 0 0" rpy="0 0 0" />
        <inertia ixx="0.001"  ixy="0.0"  ixz="0.0"
                 iyy="0.001"  iyz="0.0"
                 izz="0.001" />
      </inertial>

      <visual name="${name}_plate_frame_visual">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_plate_frame_visual_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </visual>

      <collision name="${name}_plate_frame_collision">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry name="${name}_plate_frame_collision_geom">
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision>
    </link>

    <gazebo name="gazebo_material" reference="${name}_plate_frame_visual">
      <material value="PR2/Blue" />
    </gazebo>
    
  </macro>


  <!--                    Calibration                            -->
 
  <macro name="head_calibrator">
    <controller name="cal_head_pan" topic="cal_head_pan"
                type="JointUDCalibrationControllerNode">
      <calibrate joint="head_pan_joint"
                 actuator="head_pan_motor"
                 transmission="head_pan_trans"
                 velocity="-1.5" />
      <pid p="2.0" i="0.0" d="0" iClamp="1.0" />
    </controller>

    <controller name="cal_head_tilt" topic="cal_head_tilt"
                type="JointUDCalibrationControllerNode">
      <calibrate joint="head_tilt_joint"
                 actuator="head_tilt_motor"
                 transmission="head_tilt_trans"
                 velocity="-0.7" />
      <pid p="4.0" i="0.0" d="0" iClamp="5.0" />
    </controller>
  </macro>

  <macro name="head_calibrator_alpha2">
    <controller name="cal_head_pan" topic="cal_head_pan"
                type="JointUDCalibrationControllerNode">
      <calibrate joint="head_pan_joint"
                 actuator="head_pan_motor"
                 transmission="head_pan_trans"
                 velocity="1.5" />
      <pid p="2.0" i="0.1" d="0" iClamp="1.0" />
    </controller>

    <controller name="cal_head_tilt" topic="cal_head_tilt"
                type="JointUDCalibrationControllerNode">
      <calibrate joint="head_tilt_joint"
                 actuator="head_tilt_motor"
                 transmission="head_tilt_trans"
                 velocity="-1.0" />
      <pid p="20.0" i="5.0" d="0" iClamp="1.0" />
    </controller>
  </macro>


  <macro name="head_calibrator_alpha2a">
    <controller name="cal_head_pan" topic="cal_head_pan"
                type="JointUDCalibrationControllerNode">
      <calibrate joint="head_pan_joint"
                 actuator="head_pan_motor"
                 transmission="head_pan_trans"
                 velocity="1.5" />
      <pid p="3.0" i="0.0" d="0" iClamp="1.0" />
    </controller>

    <controller name="cal_head_tilt" topic="cal_head_tilt"
                type="JointUDCalibrationControllerNode">
      <calibrate joint="head_tilt_joint"
                 actuator="head_tilt_motor_alpha2a"
                 transmission="head_tilt_trans"
                 velocity="-1.0" />
      <pid p="20.0" i="5.0" d="0" iClamp="1.0" />
    </controller>
  </macro>

  <macro name="head_calibrator_alpha2b">
    <controller name="cal_head_pan" topic="cal_head_pan"
                type="JointUDCalibrationControllerNode">
      <calibrate joint="head_pan_joint"
                 actuator="head_pan_motor"
                 transmission="head_pan_trans"
                 velocity="1.5" />
      <pid p="3.0" i="0.0" d="0" iClamp="1.0" />
    </controller>

    <controller name="cal_head_tilt" topic="cal_head_tilt"
                type="JointUDCalibrationControllerNode">
      <calibrate joint="head_tilt_joint"
                 actuator="head_tilt_motor_alpha2b"
                 transmission="head_tilt_trans"
                 velocity="-1.0" />
      <pid p="20.0" i="5.0" d="0" iClamp="1.0" />
    </controller>
  </macro>



  <macro name="tilting_laser_calibrator" params="name">
    <controller name="cal_${name}" topic="cal_${name}" type="JointUDCalibrationControllerNode">
      <calibrate joint="${name}_mount_joint"
                 actuator="${name}_mount_motor"
                 transmission="${name}_mount_trans"
                 velocity="-1.5" />
      <pid p=".3" i="0.1" d="0" iClamp="1.0" />
    </controller>
  </macro>

</robot>
