costmap:
  obstacle_range: 2.5
  max_obstacle_height: 2.0
  raytrace_range: 3.0
  inscribed_radius: 0.20
  circumscribed_radius: 0.25
  inflation_radius: 0.25
  cost_scaling_factor: 1.0
  lethal_cost_threshold: 100
  observation_topics: scan
  scan: {sensor_frame: frame_from_message, data_type: LaserScan, expected_update_rate: 0.2,
    observation_persistance: 0.0, marking: true, clearing: true}
